# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1.7.0
        with:
          xcode-version: 16
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
      - name: Build Demo
        run: cd Demo && xcodebuild -scheme SwiftFieldsDemo -destination 'generic/platform=iOS Simulator' build
